SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `list` (
  `idlist` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `ic` varchar(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `list`
  ADD PRIMARY KEY (`idlist`);

ALTER TABLE `list`
  MODIFY `idlist` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;